dist: trusty
sudo: false
language: go

go:
  - "1.10"

stages:
  - install
  - test

jobs:
  include:
    - stage: test
      before_script: script: bash tests/setup.sh
      script: bash tests/run.sh
    - script: bash tests/lint.sh
