dist: trusty
sudo: false
language: go

go:
  - master

stages:
  - install
  - test

jobs:
  include:
    - stage: install
      script: bash tests/setup.sh
    - stage: test
      script: bash tests/run.sh
    - script: bash tests/lint.sh
